import Head from 'next/head'
import { useAppContext } from '../context/state'
import { useEffect } from "react";
import Router from 'next/router'
import { getAuth } from "firebase/auth";
import { initializeApp } from "firebase/app"
import firebaseConfig from './api/firebase-config';

export default function Home() {
	const context = useAppContext()
	const app = initializeApp(firebaseConfig)
	const auth = getAuth(app)
	const user = auth.currentUser

	console.log(user)

	useEffect(() => {
		if ( !user ) {
			Router.push('/login')
		}
	})

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Main page</h1>
			</main>
		</div>
	)
}
